site_name: Simulador ARGOS-3
site_url: "https://github.com/arthurcadore/eng-telecom-tcc"
theme:
  name: material
  palette:
    - scheme: white
      primary: navy
      accent: navy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Início: index.md
  - Classes:
      - Datagrama: api/datagram.md
      - Codificador Convolutional: api/convolutional.md
      - Embaralhador: api/scrambler.md
      - Preâmbulo: api/preamble.md
      - Multiplexador: api/multiplexer.md
      - Codificador NRZ e MAN: api/encoder.md
      - Formatador RRC: api/formatter.md
      - Modulador: api/modulator.md
  - Transmissão: 
      - Transmissor: api/transmitter.md
  - Recepção:
      - Noise: api/noise.md
  - Plots: api/plots.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_submodules: true
