site_name: Simulador ARGOS-3
site_url: "https://github.com/arthurcadore/eng-telecom-tcc"
theme:
  name: material
  palette:
    - scheme: slate
      primary: green
      accent: green

nav:
  - Início: index.md
  - Referência da API:
      - Codificador: api/encoder.md
      - Modulador: api/modulator.md
      - Multiplexador: api/multiplexer.md
      - Preamble: api/preamble.md
      - Transmissor: api/transmitter.md
      - Convolutional: api/convolutional.md
      - Datagram: api/datagram.md
      - Formatter: api/formatter.md
      - Noise: api/noise.md
      - Plots: api/plots.md
      - Scrambler: api/scrambler.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_submodules: true
