site_name: Simulador ARGOS-3
site_url: "https://github.com/arthurcadore/simulacao-tcc"

repo_name: simulacao-tcc
repo_url: https://github.com/arthurcadore/simulacao-tcc
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  palette:
    - scheme: white
      primary: darkblue
      accent: darkblue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - header.autohide
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.code.highlight
    - content.tooltips
    - navigation.expand
    - repository.icon 
  icon:
    repo: fontawesome/brands/github 

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/hide_sidebar.js
  
extra_css:
  - assets/styles.css

nav:
  - Início: index.md
  - Componentes:
      - Datagrama: api/datagram.md
      - Codificador Convolutional: api/convolutional.md
      - Embaralhador: api/scrambler.md
      - Preâmbulo: api/preamble.md
      - Multiplexador: api/multiplexer.md
      - Codificador NRZ e MAN: api/encoder.md
      - Formatador: api/formatter.md
      - Modulador: api/modulator.md
      - Noise: api/noise.md
      - Filtro Passa-Baixa: api/lpf.md
      - Filtro Casado: api/matchedfilter.md
      - Decisor: api/sampler.md
      - Viterbi: api/viterbi.md
  - Transmissor: api/transmitter.md
  - Receptor: api/receiver.md
  - Plotter: api/plots.md
  - Extras: 
      - BER vs SNR: api/bersnr.md
      - Data Import/Export: api/data.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_submodules: true
            members_order: source

badges: 
  - name: Stars 
    image: https://img.shields.io/github/stars/arthurcadore/simulacao-tcc?style=social 
    link: https://github.com/arthurcadore/simulacao-tcc/stargazers 
  - name: Forks 
    image: https://img.shields.io/github/forks/arthurcadore/simulacao-tcc?style=social 
    link: https://github.com/arthurcadore/simulacao-tcc/network/members 

markdown_extensions:
  - pymdownx.arithmatex:  
      generic: true
  - toc:  
  - admonition:
