site_name: Simulador ARGOS-3
site_url: "https://github.com/arthurcadore/simulacao-tcc"

repo_name: simulacao-tcc
repo_url: https://github.com/arthurcadore/simulacao-tcc
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - header.autohide
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.code.highlight
    - content.tooltips
    - navigation.expand
    - navigation.top
    - repository.icon 
  icon:
    repo: fontawesome/brands/github 

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - site/hide_sidebar.js
  
extra_css:
  - site/styles.css

nav:
  - Início: index.md
  - Instalação: 
      - Instalação pip: api/api.md
      - Instalação manual: api/guia.md
      - Changelog: changelog.md
  - Componentes:
      - Datagrama: api/datagram.md
      - Codificador Convolutional: api/convolutional.md
      - Embaralhador: api/scrambler.md
      - Preâmbulo: api/preamble.md
      - Multiplexador: api/multiplexer.md
      - Codificador de Canal: api/encoder.md
      - Formatador: api/formatter.md
      - Modulador: api/modulator.md
      - Detector: api/detector.md
      - Filtro Passa-Baixa: api/lpf.md
      - Filtro Casado: api/matchedfilter.md
      - Sincronizador: api/synchronizer.md
      - Decisor: api/sampler.md
      - Decodificador Viterbi: api/viterbi.md
  - Transmissor: api/transmitter.md
  - Canal: 
      - Canal: api/channel.md
      - Adição Ruído SNR: api/noiseSNR.md
      - Adição Ruído EBN0: api/noiseEBN0.md
  - Receptor: api/receiver.md
  - Extras: 
      - BER vs SNR: api/bersnr.md
      - Plotter: api/plots.md
      - Data Import/Export: api/data.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/argos3]
          options:
            show_source: false
            show_submodules: true
            members_order: source

badges: 
  - name: Stars 
    image: https://img.shields.io/github/stars/arthurcadore/simulacao-tcc?style=social 
    link: https://github.com/arthurcadore/simulacao-tcc/stargazers 
  - name: Forks 
    image: https://img.shields.io/github/forks/arthurcadore/simulacao-tcc?style=social 
    link: https://github.com/arthurcadore/simulacao-tcc/network/members 
  - name: Release
    image: https://img.shields.io/github/v/release/arthurcadore/simulacao-tcc?style=flat
    link: https://github.com/arthurcadore/simulacao-tcc/releases/latest
    
markdown_extensions:
  - pymdownx.arithmatex:  
      generic: true
  - toc:  
  - admonition:
