site_name: Simulador ARGOS-3
site_url: "https://github.com/arthurcadore/eng-telecom-tcc"

theme:
  name: material
  logo: assets/icon.svg
  palette:
    - scheme: slate
      primary: darkblue
      accent: darkblue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: darkblue
      accent: darkblue
      scheme: slate
    - scheme: default
      primary: darkblue
      accent: darkblue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - header.autohide
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.tooltips
    - content.code.annotate
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.code.highlight
    - content.code.fold
    - repository.icon 
  icon:
    repo: fontawesome/brands/github 

repo_name: arthurcadore/eng-telecom-tcc
repo_url: https://github.com/arthurcadore/eng-telecom-tcc
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arthurcadore/eng-telecom-tcc
      name: GitHub

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - assets/styles.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arthurcadore/eng-telecom-tcc
      name: GitHub

nav:
  - Início: index.md
  - Classes:
      - Datagrama: api/datagram.md
      - Codificador Convolutional: api/convolutional.md
      - Decodificador Viterbi: api/viterbi.md
      - Embaralhador: api/scrambler.md
      - Preâmbulo: api/preamble.md
      - Multiplexador: api/multiplexer.md
      - Codificador NRZ e MAN: api/encoder.md
      - Formatador RRC: api/formatter.md
      - Modulador: api/modulator.md
  - Transmissão: 
      - Transmissor: api/transmitter.md
  - Recepção:
      - Noise: api/noise.md
  - Plots: api/plots.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_submodules: true
