BITSTREAM_X = "Bit Index"
BITSTREAM_Y = "Bit Value"
SYMBOLS_X = "Symbol Index"
SYMBOLS_Y = "Amplitude"
TIMEDOMAIN_X = "Time"
TIMEDOMAIN_Y = "Amplitude"
FREQUENCY_X = "Frequency"
FREQUENCY_Y = "Magnitude (dB)"
COLOR_I = "darkgreen"
COLOR_Q = "navy"
COLOR_COMBINED = "purple"
COLOR_IMPULSE = "black"
COLOR_AUX1 = "orange"
COLOR_AUX2 = "blue"
COLOR_AUX3 = "green"
COLOR_AUX4 = "red"

